from os import getenv

DB_USERNAME=getenv("DB_USERNAME")
DB_PASSWORD=getenv("DB_PASSWORD")
JWT_SECRET_KEY=getenv("JWT_SECRET_KEY")

DUMMY_USERNAME=getenv("DUMMY_USERNAME")
DUMMY_PASSWORD=getenv("DUMMY_PASSWORD")
DUMMY_EMAIL=getenv("DUMMY_EMAIL")
DUMMY_RESTAURANT=getenv("DUMMY_RESTAURANT")